version: '3.8'
services:
  mitm:
    image: mitmproxy/mitmproxy
    ports:
      - "443:443"
    command: mitmdump -v
      --mode reverse:https://example.dev:443@443 --ssl-insecure --set keep_host_header
    volumes:
      - ./ca/mitmproxy-ca.pem:/home/mitmproxy/.mitmproxy/mitmproxy-ca.pem
      - ./mitm/hosts:/etc/hosts
  nginx:
    image: nginx:1.25.1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/00-generate-ssl-certs.sh:/docker-entrypoint.d/00-generate-ssl-certs.sh
      - ./ca:/etc/nginx/certs/ca
    networks:
      default:
        ipv4_address: 172.28.0.100
networks:
  default:
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
