version: '3.8'
services:
  nginx:
    image: nginx:1.25.1
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/00-generate-ssl-certs.sh:/docker-entrypoint.d/00-generate-ssl-certs.sh
      - ./ca:/etc/nginx/certs/ca
